version: '1.0'
name: CI
displayName: CI
triggers:
  manual:
  push:
    branches:
stages:
  - stage:
    name: Build All and Test All
    displayName: 编译
    steps:
      - step: build@nodejs
        name: Build All & Test All
        displayName: Nodejs 构建
        nodeVersion: 15.12.0
        commands:
          - printenv
          - git config user.name gitbot
          - git config user.email gitbot@gmail.com
          - npm config set registry=http://registry.npmjs.org
          - npm i -g pnpm@7.18.0
          - pnpm --version
          - yarn --version
          - echo '${GITEE_COMMIT_MESSAGE}' | node common/scripts/install-run-rush.js -q commitlint --config common/autoinstallers/rush-lint-staged/commitlint.config.js
          - node common/scripts/install-run-rush.js install
        # 非必填字段，开启后表示将构建产物暂存，但不会上传到制品库中，7天后自动清除
        artifacts:
          # 构建产物名字，作为产物的唯一标识可向下传递，支持自定义，默认为BUILD_ARTIFACT。在下游可以通过${BUILD_ARTIFACT}方式引用来获取构建物地址
          - name: BUILD_ARTIFACT
            # 构建产物获取路径，是指代码编译完毕之后构建物的所在路径
            path:
              - ./output
